version: "3.7"
services:
 mysql:
  container_name: mysql
  image: mysql:8.0.22
  ports:
   - 3306:3306
  volumes:
   - /Users/hong/dumps/docker/parking:/docker-entrypoint-initdb.d
  command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
  environment:
   MYSQL_ROOT_PASSWORD: fbrjsgml_2
   MYSQL_USER: admin
   MYSQL_DATABASE: parking
   MYSQL_PASSWORD: 1234
   TZ: Asia/Seoul
 
 chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210604
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

 selenium-hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210604
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
 parking-service:
  container_name: parking-service
  build:
   context: .
   dockerfile: Dockerfile
  environment:
   MYSQL_ADDRESS: mysql
   MYSQL_USERNAME: admin
   MYSQL_PASSWORD: 1234
  ports:
   - 8080:8080
  restart: always
  links:
   - mysql
  depends_on:
   - mysql
